language: node_js
node_js:
  - "node"
cache:
  - npm
branches:
  only:
    - master
script:
  - npm run lint
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $TRAVISTOKEN
  local_dir: dist
  verbose: true
  on:
    branch: master
